const assert=require('node:assert/strict');const{spawn}=require('node:child_process');const crypto=require('node:crypto');const baseUrl=process.env.TEST_BASE_URL||'http://127.0.0.1:8080';
async function request(path,options={}){const r=await fetch(baseUrl+path,{...options,headers:{'content-type':'application/json','origin':baseUrl,...(options.headers||{})}});const body=await r.json().catch(()=>({}));return{r,body};}
async function signup(email){const password=`C${crypto.randomBytes(24).toString('base64url')}!`;const x=await request('/api/auth/sign-up/email',{method:'POST',body:JSON.stringify({name:'Contact Test',email,password})});assert.equal(x.r.status,200,JSON.stringify(x.body));const cookie=x.r.headers.get('set-cookie');assert.ok(cookie);return cookie.split(',').map(v=>v.trim().split(';')[0]).join('; ');}
(async()=>{const server=spawn(process.execPath,['server/src/index.js'],{env:{...process.env,PORT:'8080'},stdio:['ignore','pipe','pipe']});try{for(let i=0;i<30;i++){try{if((await request('/api/health')).r.ok)break}catch{}await new Promise(r=>setTimeout(r,200));}
const c1=await signup('contacts-'+crypto.randomUUID()+'@example.test');const owner=await request('/api/owners',{method:'POST',headers:{Cookie:c1},body:JSON.stringify({name:'Contact Owner'})});assert.equal(owner.r.status,201,JSON.stringify(owner.body));
const created=await request('/api/contacts',{method:'POST',headers:{Cookie:c1},body:JSON.stringify({owner_id:owner.body.owner.id,first_name:'Test',last_name:'Contact',title:'Owner Representative',phone:'555-0100',email:'contact@example.test'})});assert.equal(created.r.status,201,JSON.stringify(created.body));const id=created.body.contact.id;
const detail=await request('/api/contacts/'+id,{headers:{Cookie:c1}});assert.equal(detail.r.status,200,JSON.stringify(detail.body));assert.equal(detail.body.phones.length,1);assert.equal(detail.body.emails.length,1);
const updated=await request('/api/contacts/'+id,{method:'PATCH',headers:{Cookie:c1},body:JSON.stringify({title:'Updated Representative',mailing_address:'Updated Address'})});assert.equal(updated.r.status,200,JSON.stringify(updated.body));assert.equal(updated.body.contact.title,'Updated Representative');
const c2=await signup('contacts2-'+crypto.randomUUID()+'@example.test');const hidden=await request('/api/contacts/'+id,{headers:{Cookie:c2}});assert.equal(hidden.r.status,404,JSON.stringify(hidden.body));const crossUpdate=await request('/api/contacts/'+id,{method:'PATCH',headers:{Cookie:c2},body:JSON.stringify({title:'Cross Org'})});assert.equal(crossUpdate.r.status,404,JSON.stringify(crossUpdate.body));
const deleted=await request('/api/contacts/'+id,{method:'DELETE',headers:{Cookie:c1}});assert.equal(deleted.r.status,204);const gone=await request('/api/contacts/'+id,{headers:{Cookie:c1}});assert.equal(gone.r.status,404);
console.log('Contact CRUD lifecycle, cascade channels, audit path, and organization isolation checks passed.');}finally{server.kill('SIGTERM')}})().catch(e=>{console.error(e);process.exit(1)})